const subject = ["BOTANY", "CHEMISTRY", "PHYSICS", "ZOOLOGY"];

Map topics = {
  "BOTANY": [
    "Anatomy of Flowering Plants",
    "Biodiversity and Conservation",
    "Biological Classification",
    "Cell - The Unit of Life",
    "Cell Cycle and Cell Division",
    "Ecosystem",
    "Environmental Issues",
    "Microbes in Human Welfare",
    "Mineral Nutrition",
    "Molecular Basis of Inheritance",
    "Morphology of Flowering Plants",
    "Organisms and Populations",
    "Photosynthesis in Higher Plants",
    "Plant Growth and Development",
    "Principles of Inheritance & Variation",
    "Reproduction in Organisms",
    "Respiration in Plants",
    "Sexual Reproduction in Flowering Plants",
    "Strategies for Enhancement in Food Production",
    "The Living World",
    "The Plant Kingdom",
    "Transport in Plants"
  ],
  "CHEMISTRY": [
    "Alcohols,Phenols and Ethers",
    "Aldehydes, Ketones and Carboxylic Acids",
    "Amines",
    "Biomolecules",
    "Chemical Bonding and Molecular Structure",
    "Chemical Kinetics",
    "Chemistry in Everyday Life",
    "Classification of Elements and Periodicity in Properties",
    "Coordination Compounds",
    "Electrochemistry",
    "Environmental Chemistry",
    "Equilibrium",
    "General Principles and Processes of Isolation of Elements",
    "Haloalkanes and Haloarenes",
    "Hydrocarbons",
    "Hydrogen",
    "Organic Chemistry - Some Basic Principles And Techniques",
    "Polymers",
    "Redox Reactions",
    "Solutions",
    "Some Basic Concepts Of Chemistry",
    "States of Matter",
    "Structure of Atoms",
    "Surface Chemistry",
    "The d and f Block Elements",
    "The p-Block Elements (XI)",
    "The p-Block Elements (XII)",
    "The s-Block Elements",
    "The Solid State",
    "Thermodynamics"
  ],
  "PHYSICS": [
    "Alternating Current",
    "Atoms",
    "Current Electricity",
    "Dual Nature of Radiation and Matter",
    "Electric Charges and Fields",
    "Electromagnetic Induction",
    "Electromagnetic Waves",
    "Electrostatic Potential and Capacitance",
    "Gravitation",
    "Kinetic Theory of Gases",
    "Laws of Motion",
    "Magnetism and Matter",
    "Mathematical Tools",
    "Mechanical Properties of Fluids",
    "Mechanical Properties of Solids",
    "Motion in A Plane",
    "Motion in A Straight Line",
    "Moving Charges and Magnetism",
    "Nuclei",
    "Oscillations",
    "Ray Optics and Optical Instruments",
    "Semiconductor Electronics",
    "Systems of Particles and Rotational Motion",
    "Thermal Properties of Matter",
    "Thermodynamics",
    "Units and Measurement",
    "Wave Optics",
    "Waves",
    "Work, Energy and Power"
  ],
  "ZOOLOGY": [
    "Animal Kingdom",
    "Biomolecules",
    "Biotechnology and its Applications",
    "Biotechnology- Principles and Processes",
    "Body Fluids and Circulation",
    "Breathing and Exchange of Gases",
    "Chemical Coordination and Integration",
    "Digestion and Absorption",
    "Evolution",
    "Excretory Products and their Elimination",
    "Human Health and Disease",
    "Human Reproduction",
    "Locomotion and Movement",
    "Neural Control and Coordination",
    "Reproductive Health",
    "Structural Organisation in Animals"
  ]
};
